name: Auto Upload files to release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # 获取latest release tag，cut切割无关内容。和仓库中LocalReleaseTag对比，之后输出tag给之后的步骤
      - name: Set Version
        id: set-version
        run: |
          TAG=$(wget --no-check-certificate -qO- https://api.github.com/repos/c0re100/qBittorrent-Enhanced-Edition/tags | grep 'name' | cut -d\" -f4 | head -1 | cut -c 9- )

          OnlineReleaseTag=${TAG}
          LocalReleaseTag=$(cat ReleaseTag | head -n1)

          echo "LocalReleaseTag=$(cat ReleaseTag | head -n1)"
          echo "OnlineReleaseTag=${TAG}"

          if [ "${LocalReleaseTag}" != "${OnlineReleaseTag}" ]
          then
             echo "::set-output name=version::${TAG}"
             echo "::set-output name=status::success"
          fi

      - name: Dowload release
        if: steps.set-version.outputs.status == 'success'
        run: |
          mkdir ./qbittorrent
          cd ./qbittorrent
          wget -q https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/download/release-${{ steps.set-version.outputs.version }}/qbittorrent-nox_aarch64-linux-musl_static.zip
          wget -q https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/download/release-${{ steps.set-version.outputs.version }}/qbittorrent-nox_arm-linux-musleabi_static.zip
          wget -q https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/download/release-${{ steps.set-version.outputs.version }}/qbittorrent-nox_linux_x64_static.zip


      - name: Upload files to release
        if: steps.set-version.outputs.status == 'success'
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: qBittorrent Enhanced Edition v${{ steps.set-version.outputs.version }}
          tag_name: ${{ steps.set-version.outputs.version }}
          # body_path: Changelog
          files: |
            ./qbittorrent/*.zip
